Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: org.example.functions.ProfesoresFunction
      CodeUri: C:\Users\Alumno_FP\IdeaProjects\EjLambda2Repaso
      Runtime: java17
      Architectures:
        - x86_64